#include "pch.h"

int main()
{
	try
	{

	}
	catch (const std::exception& e)
	{
		std::cerr << "Error occurred: " << e.what() << std::endl;
	}
	return 0;
}